version: "3.9"

services:

  postgres:
    image: postgres:14.6-alpine
    volumes:
      - ToDo_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
volumes:
 ToDo_data: